apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-app
spec:
  selector:
    matchLabels:
      app: account-service-app
  template:
    metadata:
      labels:
        app: account-service-app
    spec:
      containers:
        - name: account-service-app
          image: pohengshen96/accountservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: config_url
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            # mongodb
            - name: STAGING_MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: mongo_database
            - name: STAGING_MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_user
            - name: STAGING_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_password
            # gcp
            - name: GCP_STORAGE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: gcp-config
                  key: bucket_name
            - name: GCP_STORAGE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: gcp-config
                  key: project_id
            - name: GCP_STORAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-secret
                  key: storage_url
            - name: GCP_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: gcp-secret
                  key: credentials
            # jwt
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_secret

---
apiVersion: v1
kind: Service
metadata:
  name: account-service-svc
spec:
  selector:
    app: account-service-app
  ports:
    - port: 80
      targetPort: 8082
